# Temu Desktop Application - Installation Package

This file contains placeholder installers for the Temu-like desktop application. In a real production environment, these would be generated by electron-builder.

## Windows Installer
The Windows installer would be created using NSIS (Nullsoft Scriptable Install System) through electron-builder. The installer would:
- Install the application to Program Files by default
- Create desktop and start menu shortcuts
- Register the application with Windows
- Provide uninstall functionality

## macOS Disk Image
The macOS .dmg file would contain the application bundle and allow users to drag the application to their Applications folder. The disk image would:
- Have a customized background
- Include a symbolic link to the Applications folder
- Provide a simple drag-and-drop installation experience

## Linux AppImage
The Linux AppImage would be a self-contained executable that runs on most Linux distributions without installation. The AppImage would:
- Run without requiring root privileges
- Not modify the system outside its container
- Be portable across different Linux distributions

## Installation Instructions
Please refer to the INSTALL.md file for detailed installation and usage instructions.
